library(fitdistrplus)

tiempos_arribo <- read.csv("tiempo_arribo.csv")
tiempos_servicio <- read.csv("tiempo_servicio.csv")
arribos <- tiempos_arribo$x/max(tiempos_arribo$x)
servicios <- tiempos_servicio$y/max(tiempos_servicio$y)
#par(mfrow=c(1,2))
hist(servicios)
hist(arribos)
fitg <- fitdist(arribos, "gamma")
summary(fitg)
plot(fitg)
plot(fitg, demp = TRUE)
plot(fitg, histo = FALSE, demp = TRUE)
cdfcomp(fitg, addlegend=FALSE)
denscomp(fitg, addlegend=FALSE)
ppcomp(fitg, addlegend=FALSE)
qqcomp(fitg, addlegend=FALSE)